version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    container_name: postgres
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    container_name: backend
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
  frontend:
    container_name: frontend
    build: ./frontend/
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/
  gateway:
    container_name: gateway
    build: ./nginx/    
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles
