version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: taski_db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    container_name: taski_backend
    image: djonick/kittygram_backend
    depends_on:
      - db
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
  frontend:
    container_name: taski_frontend
    image: djonick/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    container_name: taski_gateway
    image: djonick/kittygram_gateway
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles
      - media:/media
